Repository Utils4J/JavaUtils, pull requests merged in 2024-01, with the labels that each got.

#2 DataType
  src/main/java/de/mineking/javautils/database/DatabaseManager.java
  src/main/java/de/mineking/javautils/database/TableImpl.java
  src/main/java/de/mineking/javautils/database/TypeMapper.java
  src/main/java/de/mineking/javautils/database/type/DataType.java
  src/main/java/de/mineking/javautils/database/type/PostgresType.java
Labels: type: feature

#3 IO
  src/main/java/de/mineking/javautils/io/BufferUtils.java
  src/main/java/de/mineking/javautils/io/FileUtils.java
Labels: priority: normal, type: feature

#4 Add TypeMapper#UUID
  src/main/java/de/mineking/javautils/database/DatabaseManager.java
  src/main/java/de/mineking/javautils/database/TypeMapper.java
Labels: priority: normal, type: feature

#5 Make delete return int (number of deleted rows)
  src/main/java/de/mineking/javautils/database/Table.java
  src/main/java/de/mineking/javautils/database/TableImpl.java
Labels: priority: normal, type: improvement

#7 Add Column#modifier
  src/main/java/de/mineking/javautils/database/Column.java
  src/main/java/de/mineking/javautils/database/TableImpl.java
Labels: priority: normal, type: feature

#8 Update insert methods
  .github/workflows/check.yml
  build.gradle
  src/main/java/de/mineking/javautils/database/DataClass.java
  src/main/java/de/mineking/javautils/database/Table.java
  src/main/java/de/mineking/javautils/database/TableImpl.java
  src/main/java/de/mineking/javautils/database/exception/ConflictException.java
  src/main/java/de/mineking/javautils/database/exception/SQLException.java
  src/test/java/ArrayTest.java
  src/test/java/CustomTableTest.java
  src/test/java/DatabaseTest.java
  src/test/java/KeyTest.java
  src/test/java/data/CustomTable.java
  src/test/java/data/KeyTestClass.java
  src/test/java/data/TE.java
  src/test/java/data/TestClass.java
  src/test/java/database/InsertTest.java
Labels: priority: normal, type: feature, type: improvement

#9 implemented TryCatch
  src/main/java/de/mineking/javautils/function/ThrowingConsumer.java
  src/main/java/de/mineking/javautils/function/ThrowingFunction.java
  src/main/java/de/mineking/javautils/function/ThrowingRunnable.java
  src/main/java/de/mineking/javautils/function/ThrowingSupplier.java
  src/main/java/de/mineking/javautils/function/TryCatch.java
Labels: priority: normal, type: feature

#10 Add Column#unique
  src/main/java/de/mineking/javautils/database/Column.java
  src/main/java/de/mineking/javautils/database/TableImpl.java
Labels: priority: normal, type: feature
